Initial commit of ported C# code, readme, and bicep
Azure-Samples/function-dotnet-ai-openai-chatgpt pull request #1
Opened 2024-12-13 22:36 UTC by paulyuk

## Purpose
C# / .NET 8 port of the Chat with Azure OpenAI Functions samples series

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

2024-12-14 02:03 UTC, paulyuk commented
Tested locally and in Azure using `azd up`

2025-01-06 21:55 UTC, greenie-msft approved these changes

2025-01-07 17:49 UTC, lilyjma requested changes
Minor suggestions.

2025-01-07 17:49 UTC, lilyjma commented on README.md
> +5) Add this `local.settings.json` file to the root of the repo folder to simplify local development.  Replace `AZURE_OPENAI_ENDPOINT` with your value from step 4.  Optionally you can choose a differe
```suggestion
5) Add this `local.settings.json` file to the **app** folder to simplify local development.  Replace `AZURE_OPENAI_ENDPOINT` with your value from step 4.  Optionally you can choose a different model deployment in `CHAT_MODEL_DEPLOYMENT_NAME`.  This file will be gitignored to protect secrets from committing to your repo, however by default the sample uses Entra identity (user identity and mananaged identity) so it is secretless.  
```

2025-01-07 17:49 UTC, lilyjma commented on README.md
> +
```suggestion
> **Note:**  
> If you run into the following error, go to Azure portal and find the function app resource. Add the tag `azd-service-name:api` to the app.
>
> ERROR: error executing step command 'deploy --all': getting target resource: resource not found: unable to find a resource tagged with 'azd-service-name: api'. Ensure the service resource is correctly tagged in your infrastructure configuration, and rerun provision
```

2025-01-07 19:27 UTC, paulyuk commented on README.md
> +
Thank you.  Since we determined this is internal to our company network I think we can wait on adding this for now.

2025-01-07 19:27 UTC, merged